# Custom Language File for Launcher Customizer

[ejs.app]
title = "Happy Tycoon Launcher"

[ejs.landing]
mediaHomeURL = "#"
mediaLinkURL = "#"
mediaMapURL = "#"
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "즐겁듀밸리 시즌1"
welcomeDescription = "2026년 즐겁다 스타듀밸리 모드 마인크래프트 서버"
welcomeDescCTA = "힐링하고 가세요"
